language: node_js
node_js:
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .deploy/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- yarn install
script:
- yarn docs:build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: docs/.vuepress/dist
#   github_token: "$GITHUB_TOKEN"
#   keep_history: true
#   on:
#     branch: master
addons:
  ssh_known_hosts: $DEPLOY_HOST
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet docs/.vuepress/dist $DEPLOY_PATH
  on:
    branch: master